### ISSUE TITLE
Figure out how to add multiple origins and domains to a single service, redirecting them accordingly

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/bypass-mirrors#4]
Claimed to be possible, see https://docs.fastly.com/guides/performance-tuning/routing-assets-to-different-origins

**Comment by maxpearl** [comment]
Basically the trick is use the fastly domain as the condition for both the origin and the header:

`req.http.host ~ "<abbr>.global.ssl.fastly.net"`
