### ISSUE TITLE
Create a script that takes a new domain as an input and deploys containers and mirrors and updates the json file upon success!

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/bypass-mirrors#6]

**Comment by maxpearl** [comment]
Automated creation of Cloudfront CDN distributions has been done, but this might need custom headers via lambda.

**Comment by maxpearl** [comment]
I think we can call this done. Repo here: https://github.com/OpenTechFund/bypass-otf_proxy There are still some things to implement, but we can track issues with that there.
